import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { StrategyKind as PrismaStrategyKind, type PlanningScenario as PrismaPlanningScenario } from '@prisma/client';
import type {
  CashflowsResponse,
  DataQualityWarning,
  FinancialProfile,
  FinancialWorkspaceResponse,
  ReportingYearFacts,
  StrategyBenchmark,
  StrategyKind,
} from '@fremont/shared';
import { STRATEGY_KINDS } from '@fremont/shared';
import type { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../common/prisma.service';
import { ProjectionService } from '../projection/projection.service';

type StrategyCapital = {
  capital: number;
  capitalYear: number | null;
};

const STRATEGY_ASSET_CLASS = 'Fremont Strategy';
const STRATEGY_FROM_DB: Record<PrismaStrategyKind, StrategyKind> = {
  [PrismaStrategyKind.Liquidity_Program]: 'Liquidity Program',
  [PrismaStrategyKind.OpCos]: 'OpCos',
  [PrismaStrategyKind.BF_Global]: 'BF Global',
  [PrismaStrategyKind.Opportunities_Fund]: 'Opportunities Fund',
};

const isStrategyKind = (value: string): value is StrategyKind =>
  (STRATEGY_KINDS as readonly string[]).includes(value);

const toYear = (value: unknown): number | null => {
  const parsed = Number(value);
  if (!Number.isInteger(parsed)) return null;
  return parsed;
};

@Injectable()
export class ReportingService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly projectionService: ProjectionService,
  ) {}

  private async ensureBaselineScenarioForUser(user: AuthenticatedUser, year: number): Promise<void> {
    const existing = await this.prisma.planningScenario.findFirst({
      where: { ownerId: user.id },
      select: { id: true },
    });
    if (existing) return;

    await this.prisma.planningScenario.create({
      data: {
        ownerId: user.id,
        name: 'Base Case',
        startYear: year,
        horizonYears: 20,
        baseNetWorth: 0,
        baseLiquidity: 0,
        inputs: {
          annualIncome: 1_200_000,
          annualSpending: 800_000,
          taxRate: 0.35,
          growthRate: 0.05,
          opcosPct: 0,
        },
        events: [],
      },
    });
  }

  private async ensureCurrentYearTransaction(year: number): Promise<void> {
    const currentYear = new Date().getFullYear();
    if (year !== currentYear) return;

    const start = new Date(Date.UTC(year, 0, 1));
    const end = new Date(Date.UTC(year + 1, 0, 1));

    const existing = await this.prisma.transaction.findFirst({
      where: {
        date: {
          gte: start,
          lt: end,
        },
      },
      select: { id: true },
    });
    if (existing) return;

    await this.prisma.transaction.create({
      data: {
        date: start,
        description: 'Opening Balance',
        amount: 0,
        category: 'Transfer',
        tags: ['autogenerated', 'opening-balance'],
      },
    });
  }

  private canReadScenario(user: AuthenticatedUser, scenario: PrismaPlanningScenario): boolean {
    return user.role === 'ADMIN' || scenario.ownerId === user.id;
  }

  private normalizeYear(yearRaw: unknown): number {
    const parsed = Number(yearRaw);
    if (!Number.isInteger(parsed)) return new Date().getFullYear();
    return Math.max(1900, Math.min(3000, parsed));
  }

  private normalizeAssumptions(input: Record<string, unknown> | undefined): FinancialProfile['assumptions'] {
    const taxRateRaw = Number(input?.taxRate ?? 0);
    const taxRate = Number.isFinite(taxRateRaw) ? Math.max(0, Math.min(1, taxRateRaw)) : 0;
    const taxBasis = input?.taxBasis === 'net_income' ? 'net_income' : 'gross_income';
    const inflationRateRaw = Number(input?.inflationRate);
    const returnRateRaw = Number(input?.returnRate);

    return {
      taxRate,
      taxBasis,
      inflationRate: Number.isFinite(inflationRateRaw) ? inflationRateRaw : undefined,
      returnRate: Number.isFinite(returnRateRaw) ? returnRateRaw : undefined,
    };
  }

  private async getUserProfile(user: AuthenticatedUser): Promise<FinancialProfile> {
    const row = await this.prisma.financialProfile.findUnique({ where: { ownerId: user.id } });
    if (!row) {
      return {
        userId: user.id,
        baseNetWorth: 0,
        baseLiquidity: 0,
        assumptions: {
          taxRate: 0,
          taxBasis: 'gross_income',
        },
        updatedAt: new Date().toISOString(),
      };
    }

    return {
      userId: user.id,
      baseNetWorth: row.baseNetWorth,
      baseLiquidity: row.baseLiquidity,
      assumptions: this.normalizeAssumptions((row.assumptions as Record<string, unknown>) ?? {}),
      updatedAt: row.updatedAt.toISOString(),
    };
  }

  private async getUserCashflows(user: AuthenticatedUser): Promise<CashflowsResponse> {
    const rows = await this.prisma.planningCashflowItem.findMany({
      where: { ownerId: user.id },
      orderBy: [{ kind: 'asc' }, { startYear: 'asc' }, { name: 'asc' }],
    });

    const income: CashflowsResponse['income'] = [];
    const outflow: CashflowsResponse['outflow'] = [];

    rows.forEach((row) => {
      const mapped = {
        id: row.id,
        name: row.name,
        amount: row.amount,
        start: row.startYear,
        end: row.endYear,
      };
      if (row.kind === 'Income') income.push(mapped);
      else outflow.push(mapped);
    });

    return { income, outflow };
  }

  private findBaselineScenario(scenarios: PrismaPlanningScenario[]): PrismaPlanningScenario | null {
    if (scenarios.length === 0) return null;
    return scenarios.find((scenario) => scenario.name === 'Base Case') ?? scenarios[0];
  }

  private buildStrategyCapitalByYear(
    positions: Array<{ name: string; assetClass: string; year: number | null; value: number }>,
    year: number,
  ): Map<StrategyKind, StrategyCapital> {
    const result = new Map<StrategyKind, StrategyCapital>();

    STRATEGY_KINDS.forEach((strategy) => {
      const rows = positions.filter((position) => {
        return position.assetClass === STRATEGY_ASSET_CLASS && position.name === strategy;
      });

      const dated = rows
        .map((row) => ({ ...row, normalizedYear: toYear(row.year) }))
        .filter((row): row is typeof row & { normalizedYear: number } => row.normalizedYear !== null)
        .sort((a, b) => b.normalizedYear - a.normalizedYear);

      const latestApplicable = dated.find((row) => row.normalizedYear <= year);
      if (latestApplicable) {
        result.set(strategy, {
          capital: Number(latestApplicable.value) || 0,
          capitalYear: latestApplicable.normalizedYear,
        });
        return;
      }

      const undated = rows.find((row) => toYear(row.year) === null);
      result.set(strategy, {
        capital: Number(undated?.value) || 0,
        capitalYear: null,
      });
    });

    return result;
  }

  private buildStrategyBenchmarkMap(
    benchmarks: StrategyBenchmark[],
    year: number,
  ): { map: Map<StrategyKind, StrategyBenchmark>; fallbackYears: Map<StrategyKind, number> } {
    const rowsByStrategy = new Map<StrategyKind, StrategyBenchmark[]>();
    benchmarks.forEach((benchmark) => {
      if (!isStrategyKind(benchmark.strategy)) return;
      const rows = rowsByStrategy.get(benchmark.strategy) ?? [];
      rows.push(benchmark);
      rowsByStrategy.set(benchmark.strategy, rows);
    });

    const map = new Map<StrategyKind, StrategyBenchmark>();
    const fallbackYears = new Map<StrategyKind, number>();

    STRATEGY_KINDS.forEach((strategy) => {
      const rows = [...(rowsByStrategy.get(strategy) ?? [])].sort((a, b) => b.year - a.year);
      if (rows.length === 0) return;

      const exact = rows.find((row) => row.year === year);
      if (exact) {
        map.set(strategy, exact);
        return;
      }

      const prior = rows.find((row) => row.year <= year);
      const fallback = prior ?? rows[0];
      map.set(strategy, fallback);
      fallbackYears.set(strategy, fallback.year);
    });

    return { map, fallbackYears };
  }

  private async computeYearFacts(
    user: AuthenticatedUser,
    year: number,
    preloadedScenarios?: PrismaPlanningScenario[],
  ): Promise<ReportingYearFacts> {
    await Promise.all([
      this.ensureBaselineScenarioForUser(user, year),
      this.ensureCurrentYearTransaction(year),
    ]);

    const scenariosPromise = preloadedScenarios
      ? Promise.resolve(preloadedScenarios)
      : this.prisma.planningScenario.findMany({
          where: user.role === 'ADMIN' ? {} : { ownerId: user.id },
          orderBy: [{ createdAt: 'asc' }, { name: 'asc' }],
        });

    const [positions, transactions, strategyBenchmarks, scenarios] = await Promise.all([
      this.prisma.position.findMany({
        select: { name: true, assetClass: true, year: true, value: true, liquid: true },
      }),
      this.prisma.transaction.findMany({
        where: {
          date: {
            gte: new Date(Date.UTC(year, 0, 1)),
            lt: new Date(Date.UTC(year + 1, 0, 1)),
          },
        },
        select: { amount: true },
      }),
      this.prisma.strategyBenchmark.findMany({
        orderBy: [{ year: 'asc' }, { strategy: 'asc' }],
      }),
      scenariosPromise,
    ]);

    const baselineScenario = this.findBaselineScenario(scenarios);

    let plannedNetWorth: number | null = null;
    let plannedLiquidity: number | null = null;
    let baselineScenarioId: string | null = baselineScenario?.id ?? null;
    let baselineScenarioName: string | null = baselineScenario?.name ?? null;

    if (baselineScenario) {
      if (!this.canReadScenario(user, baselineScenario)) {
        throw new ForbiddenException('Cannot view baseline scenario');
      }
      const projected = await this.projectionService.projectScenario(user, baselineScenario.id);
      const projectedPoint = projected.points.find((point) => point.year === year);
      if (projectedPoint) {
        plannedNetWorth = projectedPoint.netWorth;
        plannedLiquidity = projectedPoint.liquidity;
      }
    }

    const actualPositionsForYear = positions.filter((position) => {
      const rowYear = toYear(position.year);
      return rowYear === null || rowYear <= year;
    });

    const actualNetWorth = actualPositionsForYear.reduce((sum, position) => sum + (Number(position.value) || 0), 0);
    const actualLiquidity = actualPositionsForYear.reduce(
      (sum, position) => sum + (position.liquid ? Number(position.value) || 0 : 0),
      0,
    );

    const transactionNetFlow = transactions.reduce((sum, transaction) => sum + (Number(transaction.amount) || 0), 0);

    const capitalByStrategy = this.buildStrategyCapitalByYear(
      positions.map((position) => ({
        name: position.name,
        assetClass: position.assetClass,
        year: position.year,
        value: position.value,
      })),
      year,
    );

    const { map: benchmarkMap, fallbackYears } = this.buildStrategyBenchmarkMap(
      strategyBenchmarks.map((benchmark) => ({
        id: benchmark.id,
        strategy: STRATEGY_FROM_DB[benchmark.strategy],
        year: benchmark.year,
        targetReturnRate: benchmark.targetReturnRate,
        actualReturnRate: benchmark.actualReturnRate,
        plannedLiquidityRate: benchmark.plannedLiquidityRate,
        actualLiquidityRate: benchmark.actualLiquidityRate,
      })),
      year,
    );

    const strategyRows = STRATEGY_KINDS.map((strategy) => {
      const capitalInfo = capitalByStrategy.get(strategy) ?? { capital: 0, capitalYear: null };
      const benchmark = benchmarkMap.get(strategy);
      const targetReturnRate = benchmark?.targetReturnRate ?? 0;
      const actualReturnRate = benchmark?.actualReturnRate ?? 0;
      const plannedLiquidityRate = benchmark?.plannedLiquidityRate ?? 0;
      const actualLiquidityRate = benchmark?.actualLiquidityRate ?? 0;
      const targetReturnValue = capitalInfo.capital * targetReturnRate;
      const actualReturnValue = capitalInfo.capital * actualReturnRate;
      const plannedLiquidityValue = capitalInfo.capital * plannedLiquidityRate;
      const actualLiquidityValue = capitalInfo.capital * actualLiquidityRate;
      return {
        strategy,
        capital: capitalInfo.capital,
        capitalYear: capitalInfo.capitalYear,
        targetReturnRate,
        actualReturnRate,
        plannedLiquidityRate,
        actualLiquidityRate,
        targetReturnValue,
        actualReturnValue,
        plannedLiquidityValue,
        actualLiquidityValue,
        returnVariance: actualReturnValue - targetReturnValue,
        liquidityVariance: actualLiquidityValue - plannedLiquidityValue,
      };
    });

    const totalReturnVariance = strategyRows.reduce((sum, row) => sum + row.returnVariance, 0);
    const totalLiquidityVariance = strategyRows.reduce((sum, row) => sum + row.liquidityVariance, 0);

    const warnings: DataQualityWarning[] = [];
    if (!baselineScenario) {
      warnings.push({
        code: 'MISSING_BASELINE_SCENARIO',
        message: 'No baseline scenario found. Create a Base Case scenario in Planning for plan-vs-actual comparisons.',
        severity: 'warning',
      });
    }

    if (baselineScenario && (plannedNetWorth === null || plannedLiquidity === null)) {
      warnings.push({
        code: 'PLAN_YEAR_OUT_OF_RANGE',
        message: `Baseline scenario does not include year ${year}.`,
        severity: 'warning',
      });
    }

    if (!strategyBenchmarks.some((benchmark) => benchmark.year === year)) {
      warnings.push({
        code: 'MISSING_STRATEGY_BENCHMARKS',
        message: `No strategy benchmark percentages configured for ${year}; using nearest available benchmark years when possible.`,
        severity: 'warning',
      });
    }

    if (fallbackYears.size > 0) {
      const strategies = STRATEGY_KINDS.filter((strategy) => fallbackYears.has(strategy)).map(
        (strategy) => `${strategy}(${fallbackYears.get(strategy)})`,
      );
      warnings.push({
        code: 'BENCHMARK_YEAR_FALLBACK',
        message: `Using benchmark year fallback for ${year}: ${strategies.join(', ')}.`,
        severity: 'info',
      });
    }

    if (!strategyRows.some((row) => row.capital > 0)) {
      warnings.push({
        code: 'MISSING_STRATEGY_CAPITAL',
        message: `No Fremont strategy capital found at or before ${year}.`,
        severity: 'warning',
      });
    }

    if (transactions.length === 0) {
      warnings.push({
        code: 'NO_TRANSACTIONS_FOR_YEAR',
        message: `No transactions recorded for ${year}.`,
        severity: 'info',
      });
    }

    return {
      year,
      strategyRows,
      totalReturnVariance,
      totalLiquidityVariance,
      returnImpactPct: actualNetWorth > 0 ? totalReturnVariance / actualNetWorth : 0,
      baselineScenarioId,
      baselineScenarioName,
      plannedNetWorth,
      plannedLiquidity,
      actualNetWorth,
      actualLiquidity,
      netWorthVariance: plannedNetWorth === null ? null : actualNetWorth - plannedNetWorth,
      liquidityVariance: plannedLiquidity === null ? null : actualLiquidity - plannedLiquidity,
      transactionNetFlow,
      warnings,
    };
  }

  async getYearFacts(user: AuthenticatedUser, yearRaw: unknown): Promise<ReportingYearFacts> {
    const year = this.normalizeYear(yearRaw);
    return this.computeYearFacts(user, year);
  }

  async getWorkspace(user: AuthenticatedUser, yearRaw: unknown): Promise<FinancialWorkspaceResponse> {
    const year = this.normalizeYear(yearRaw);

    // Fetch scenarios once and share them with computeYearFacts to avoid a duplicate query.
    const scenarios = await this.prisma.planningScenario.findMany({
      where: user.role === 'ADMIN' ? {} : { ownerId: user.id },
      orderBy: [{ createdAt: 'asc' }, { name: 'asc' }],
    });

    const [profile, cashflows, positionsCount, transactionsCount, facts] = await Promise.all([
      this.getUserProfile(user),
      this.getUserCashflows(user),
      this.prisma.position.count(),
      this.prisma.transaction.count(),
      this.computeYearFacts(user, year, scenarios),
    ]);

    return {
      year,
      profile,
      cashflows,
      positionsCount,
      transactionsCount,
      scenarios: scenarios.map((s) => ({
        id: s.id,
        name: s.name,
        startYear: s.startYear,
        horizonYears: s.horizonYears,
      })),
      facts,
    };
  }

  async compareScenarios(
    user: AuthenticatedUser,
    baselineScenarioId: string,
    comparisonScenarioId: string,
  ) {
    const [baseline, comparison] = await Promise.all([
      this.prisma.planningScenario.findUnique({ where: { id: baselineScenarioId } }),
      this.prisma.planningScenario.findUnique({ where: { id: comparisonScenarioId } }),
    ]);

    if (!baseline) throw new NotFoundException('Baseline scenario not found');
    if (!comparison) throw new NotFoundException('Comparison scenario not found');
    if (!this.canReadScenario(user, baseline) || !this.canReadScenario(user, comparison)) {
      throw new ForbiddenException('Cannot view one or more scenarios');
    }

    return this.projectionService.compareScenarios(user, baselineScenarioId, comparisonScenarioId);
  }
}
